/*
 * Copyright (c) 2022 RIC Electronics
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef _ATMEL_SAM_USART_FIXUP_H_
#define _ATMEL_SAM_USART_FIXUP_H_

/* Rev A fixes */
#if !defined(CONFIG_SOC_ATMEL_SAMS70_REVB) && 		\
	!defined(CONFIG_SOC_ATMEL_SAME70_REVB) && 	\
 	!defined(CONFIG_SOC_ATMEL_SAMV71_REVB)

/* Define the new names used in the B variants */
#define XDMAC_CC_PERID_SPI0_TX		DMA_PERID_SPI0_TX
#define XDMAC_CC_PERID_SPI1_TX		DMA_PERID_SPI1_TX
#define XDMAC_CC_PERID_SPI0_RX		DMA_PERID_SPI0_RX
#define XDMAC_CC_PERID_SPI1_RX		DMA_PERID_SPI1_RX

#define US_IDR_USART_OVRE		US_IDR_OVRE
#define US_IDR_USART_FRAME		US_IDR_FRAME
#define US_IDR_USART_PARE		US_IDR_PARE
#define US_IDR_USART_TIMEOUT		US_IDR_TIMEOUT

#define US_CSR_USART_OVRE		US_CSR_OVRE
#define US_CSR_USART_FRAME		US_CSR_FRAME
#define US_CSR_USART_PARE		US_CSR_PARE
#define US_CSR_USART_TIMEOUT		US_CSR_TIMEOUT

#define US_MR_USART_CHMODE_NORMAL 	US_MR_CHMODE_NORMAL
#define US_MR_USART_NBSTOP_2_BIT 	US_MR_NBSTOP_2_BIT
#define US_MR_USART_NBSTOP_1_BIT 	US_MR_NBSTOP_1_BIT
#define US_MR_USART_PAR_ODD 		US_MR_PAR_ODD
#define US_MR_USART_PAR_EVEN 		US_MR_PAR_EVEN
#define US_MR_USART_PAR_NO 		US_MR_PAR_NO

#define US_CR_USART_DTRDIS 		US_CR_DTRDIS
#define US_CR_USART_RTSDIS 		US_CR_RTSDIS

#endif /* Rev A fixes */

#endif /* _ATMEL_SAM_USART_FIXUP_H_ */